export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/customer/table";
export * from "@/pages/settings/settings";
export * from "@/pages/invoice/table";
export * from "@/pages/appointments/appointments";
export * from "@/pages/dashboard/inspection";
export * from "@/pages/products/table";